# Practice: NumPy Iteration Exercises
Try to solve each task below and validate your solution using assertions.

In [10]:
import numpy as np

## Exercise 1: Sum all elements
Compute the sum of all elements in a 2D array using `np.nditer`.

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
# method 1 
Sum = arr.sum()
#method 2 
sum = 0
for x in np.nditer(arr) : 
    sum += x 
    
print(Sum, sum)

## Exercise 2: Double values in-place
Double each element of a 1D array using `op_flags=['readwrite']`.

In [17]:
arr = np.arange(7)
print(arr, "\n-------------")
with np.nditer(arr, op_flags=['readwrite']) as it:
    for x in it:
        x[...] = x * 2 #modifies the original value of x and not just a copy of it 
        
print(arr)

[0 1 2 3 4 5 6] 
-------------
[ 0  2  4  6  8 10 12]


## Exercise 3: Flat iterator
Use `arr.flat` to convert a 3×3 array into a list.

In [37]:
arr = np.arange(9).reshape(3,3)
lst = [int(x) for x in arr.flat]

print(arr)
print(lst)

### using other methods like ravel 
lst = []
for x in arr.ravel() : 
    print(x, end=" ")
    lst.append(int(x))
    
print("\n",lst)
    

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
0 1 2 3 4 5 6 7 8 
 [0, 1, 2, 3, 4, 5, 6, 7, 8]


## Exercise 4: Enumerate with indices
Build a dict where keys are `(i,j)` and values are elements of a 2D array using `ndenumerate`.

In [40]:
arr = np.array([[10,20,30],[40,50,60], [70, 80, 90]])
d = {}
for idx, x in np.ndenumerate(arr):
    d[idx] = int(x)

## Bonus: Skip every other column
Using `nditer`, print elements from every 2nd column of a 2×6 array.

In [43]:
arr = np.arange(12).reshape(2,6)
res = [int(x) for x in np.nditer(arr[:, 1::2])]
print(res)

[1, 3, 5, 7, 9, 11]
