# NumPy Iterating Over Arrays
This notebook summarizes key techniques for iterating through NumPy arrays.

In [1]:
import numpy as np

## 1D Array Iteration

In [7]:
arr = np.array([1, 2, 3, 4, 5])
for x in arr:
    print(x)

1
2
3
4
5


## 2D Array: row-wise iteration

In [14]:
arr2 = np.array([[1,2,3], [4,5,6]])
for row in arr2:
    print(row)
# Nested iteration to access scalars
print("-----------")
for row in arr2:
    for x in row:
        print(x)


[1 2 3]
[4 5 6]
-----------
1
2
3
4
5
6


## 3D Array iteration

In [23]:
arr3 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr3.shape, "\n-------------")
for mat in arr3:
    print(mat)
print("-------------")
for mat in arr3:
    for row in mat:
        for x in row:
            print(x)
            
print("-----------")            
for i in range(2): 
    for j in range(2): 
        for k in range(2): 
            print(arr3[i, j, k], end=" ")

(2, 2, 2) 
-------------
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
-------------
1
2
3
4
5
6
7
8
-----------
1 2 3 4 5 6 7 8 

## Using np.nditer for flat iteration

In [45]:
arr2_flat = np.array([[1,2,3],[4,5,6]])
print(arr2_flat, "\n")
for x in np.nditer(arr2_flat):
    print(x, end=' ')
print("\n")
for x in np.nditer(arr2_flat, order="F"): 
    print(x, end=' ')


[[1 2 3]
 [4 5 6]] 

1 2 3 4 5 6 

1 4 2 5 3 6 

# Changing dtype during iteration


In [46]:
arr = np.array([1, 2, 3, 4, 5])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=np.float64):
    print(x)

1.0
2.0
3.0
4.0
5.0


# Skipping elements via slicing

### Quick reminder of slicing

In [53]:
a = np.linspace(10, 50, num=5, endpoint=True, dtype=np.int32) # [10, 20, 30, 40, 50]
print(a)
print(a[1:4])     # [20, 30, 40]
print(a[:3])      # [10, 20, 30]
print(a[::2])     # [10, 30, 50]
print(a[::-1])    # [50, 40, 30, 20, 10] (reversed)
print(a[1::2])    # [20, 40]


[10 20 30 40 50]
[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]
[20 40]


In [55]:
print(arr2, "\n")
for x in np.nditer(arr2[:, ::2]): # the first : means on all rows 
    print(x, end=' ')

[[1 2 3]
 [4 5 6]] 

1 3 4 6 

## Enumerate with np.ndenumerate

In [60]:
print(arr2, "\n--------------")
for idx, x in np.ndenumerate(arr2):
    print(idx, x)

[[1 2 3]
 [4 5 6]] 
--------------
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


### Additional 
- `arr.flat`: flat iterator over any array  
- op_flags :  
    - `'readonly'` – default  
    - `'readwrite'` – allows modifying elements  
    - `'writeonly'` – for assigning new values only

- Broadcast iteration
- Use vectorized operations instead of manual iteration when possible  

### op_flag

In [61]:
a = np.array([1, 2, 3])
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * 2  # modifies a in-place

print(a)  # Output: [2, 4, 6]


[2 4 6]


### external loop
 Combines elements into chunks (e.g., rows) instead of individual elements. Useful for performance.



In [62]:
a = np.array([[1, 2, 3], [4, 5, 6]])
for x in np.nditer(a, flags=['external_loop'], order='C'):
    print(x)  # prints [1 2 3] then [4 5 6]


[1 2 3 4 5 6]


### BroadCast

In [63]:
a = np.array([1, 2, 3])
b = np.array([[10], [20]])

for x, y in np.nditer([a, b]):
    print(x, y)


1 10
2 10
3 10
1 20
2 20
3 20


### Vectorized operations

In [64]:
a = np.array([1, 2, 3, 4])
b = a * 2
c = a + b 
print(b)  # Output: [2 4 6 8]
print(c)  # Output: [3, 6, 9, 12]

[2 4 6 8]
[ 3  6  9 12]
