# NumPy Array Manipulation - Practice Exercises (with new functons)

These exercises are based on methods from the NumPy array manipulation tutorial. Try to implement each task using the appropriate function.

In [2]:
import numpy as np 

## `reshape`
Create an array of 12 elements and reshape it to 3 rows and 4 columns.

In [4]:
a = np.arange(12)
a_r = a.reshape((3, 4))
print(a_r)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## `flatten`
Given a 2D array, flatten it into a 1D array.

In [4]:
a_f = a_r.flatten()
print(a_f)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## `ravel`
Create a 2D array and use `ravel()` to make it 1D.

In [5]:
a_ravel = a_r.ravel()
print(a_ravel)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## `transpose`
Transpose a 2x3 array.

In [7]:
t1 = np.transpose(a_r)
print(t1, "\n")
t2 = a_r.T 
print(t2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] 

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## `swapaxes`
Create a 3D array of shape (2, 3, 4) and swap axes 0 and 2.

In [15]:
b = np.arange(18)
b_r = b.reshape((2, 3, 3))
print(b_r, "\n------------")
b_s = np.swapaxes(b_r, 0, 2)
print(b_s, "\n\n", b_s.shape)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] 
------------
[[[ 0  9]
  [ 3 12]
  [ 6 15]]

 [[ 1 10]
  [ 4 13]
  [ 7 16]]

 [[ 2 11]
  [ 5 14]
  [ 8 17]]] 

 (3, 3, 2)


## `broadcast_to`
Broadcast a 1D array `[1, 2, 3]` to shape `(3, 3)`.

In [17]:
q = np.arange(3)
print(q, "\n")
q_b = np.broadcast_to(q, (3, 3))
print(q_b)

[0 1 2] 

[[0 1 2]
 [0 1 2]
 [0 1 2]]


## `expand_dims`
Add a new axis to a 1D array to make it 2D.

In [19]:
e = np.arange(5)
print(e)
e_e = np.expand_dims(e, axis=0)
print(e_e)

[0 1 2 3 4]
[[0 1 2 3 4]]


## `concatenate`
Concatenate two 2D arrays along axis 0.

In [25]:
b = np.array([[5, 6, 7, 4], [8, 9, 10, 5]])
a = np.array([[1, 2, 3], [-1, -2, -2]])
print('Concatenated:\n', np.concatenate((b, a), axis=1))

Concatenated:
 [[ 5  6  7  4  1  2  3]
 [ 8  9 10  5 -1 -2 -2]]


## `split`
Split a 1D array of 9 elements into three equal parts.

In [56]:
s = np.arange(0, 27, 3, dtype=np.int32)
print(s, "\n")

x = np.split(s, 9)
for i in range(0, 9) : 
    print(i, ": " ,x[i])

[ 0  3  6  9 12 15 18 21 24] 

0 :  [0]
1 :  [3]
2 :  [6]
3 :  [9]
4 :  [12]
5 :  [15]
6 :  [18]
7 :  [21]
8 :  [24]


## `append`
Append a row `[7, 8]` to a 2x2 array.

In [50]:
a = np.linspace(7, 8, endpoint=True, num=2, dtype=np.int32)
a = np.expand_dims(a, axis=0)
print(a, "\n")
print(np.append(a, [[1, 2]], axis=0))

[[7 8]] 

[[7 8]
 [1 2]]


## `delete`
Delete the second row of a 3x2 array.

In [37]:
d = np.arange(6)
d = d.reshape((2, 3))
print(d, "\n")
d_d = np.delete(d, 1, axis=0) # axis=0 is for deleting row and 1 is for the second row (0 base indexing) 
print(d_d)

[[0 1 2]
 [3 4 5]] 

[[0 1 2]]


## `unique`
Find unique elements in the array `[1, 2, 2, 3, 3, 3]`.

In [30]:
x = np.array([1, 2, 2, 3, 3, 3])
x_u = np.unique(x)
print(x_u)

[1 2 3]


## `repeat`
Repeat each element of `[1, 2, 3, 2]` twice.

In [64]:
a = np.array([1, 2, 3, 2])
a_repeat = np.repeat(a, 2) 
print(a_repeat)

[1 1 2 2 3 3 2 2]


## `flip`
Flip a 2D array upside down.

In [60]:
f = np.arange(15)
f = f.reshape((3, 5))
print(f, "\n-------------")

f_flip = np.flip(f)
print(f_flip)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 
-------------
[[14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


## `sort`
Sort a 1D array `[3, 1, 2]`.

In [72]:
n = np.array([3, 1, 2])
print(np.sort(n))

[1 2 3]


## `argmax`
Find the index of the maximum element in `[1, 7, 3]`.

In [71]:
m = np.array([1, 7, 3])
print(np.argmax(m))

1


## `intersect1d`
Find the common elements between `[1, 2, 3]` and `[2, 3, 4]`.

In [67]:
a1 = np.array([1, 2, 3])
a2 = np.array([2, 3, 4])

a3 = np.intersect1d(a1, a2)
print(a3)

[2 3]


## `clip`
Clip the values of `[1, 4, 7]` to stay between 2 and 5.

In [65]:
c = np.array([1, 4, 7])
c_clip = np.clip(a, 2, 5)
print(c_clip) 

[2 2 3 2]
