# NumPy Array Manipulation - Examples with Comments

This notebook includes **examples and comments** for each function/method from the TutorialsPoint NumPy Array Manipulation guide.

In [2]:
import numpy as np 

## `reshape`

In [5]:
# Reshapes an array without changing its data
a = np.arange(6)
print('a:\n', a, "\n")
print('Reshaped: \n', a.reshape((2, 3)))

a:
 [0 1 2 3 4 5] 

Reshaped: 
 [[0 1 2]
 [3 4 5]]


## `flatten`

In [6]:
# Returns a copy of the array collapsed into one dimension
a = np.array([[1, 2, 3], [4, 5, 6]])
print('a:\n', a, "\n")
print('Flattened:', a.flatten())

a:
 [[1 2 3]
 [4 5 6]] 

Flattened: [1 2 3 4 5 6]


## `ravel`

In [10]:
# Returns a flattened view of the array (if possible)
a = np.array([[1, 2], [3, 4]])
print('a:\n', a, "\n")
print('Raveled:', a.ravel())

a:
 [[1 2]
 [3 4]] 

Raveled: [1 2 3 4]


## `transpose`

In [5]:
# Permutes the dimensions of an array
a = np.array([[1, 2, 3], [4, 5, 6]])
print('a:\n', a, "\n")
print('Transposed: \n', np.transpose(a))

a:
 [[1 2 3]
 [4 5 6]] 

Transposed: 
 [[1 4]
 [2 5]
 [3 6]]


## `T`

In [8]:
# Equivalent to transpose for 2D arrays
a = np.array([[1, 2], [3, 4]])
print('a:\n', a, "\n")
print('Transposed using .T:\n', a.T)

a:
 [[1 2]
 [3 4]] 

Transposed using .T:
 [[1 3]
 [2 4]]


## `swapaxes`

In [14]:
# Swaps two axes in an array
a = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print("ndim: ", a.ndim, "dims: ", a.shape, "\n")
print('a:\n', a, "\n")
print('Swapped Axes (0,2):\n', np.swapaxes(a, 0, 2))

ndim:  3 dims:  (2, 2, 2) 

a:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 

Swapped Axes (0,2):
 [[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


## `broadcast`

In [20]:
# Demonstrates implicit broadcasting in arithmetic operations
a = np.array([1,2,3])
b = np.array([[0],[1],[2]])
print('a:\n', a, "\n")
print('b:\n', b, "\n")
print('Broadcasted Sum:\n', a + b)

a:
 [1 2 3] 

b:
 [[0]
 [1]
 [2]] 

Broadcasted Sum:
 [[1 2 3]
 [2 3 4]
 [3 4 5]]


## `broadcast_to`

In [ ]:
# Explicitly broadcast an array to a given shape
a = np.array([1,2,3,4])
print('Broadcast to (3,3):\n', np.broadcast_to(a, (5,4)))

Broadcast to (3,3):
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


## `expand_dims`

In [32]:
# Adds a new axis to an array
a = np.array([1, 2])
print('Expanded dims:\n', np.expand_dims(a, axis=0), "\n")
print('Expanded dims:\n', np.expand_dims(a, axis=1), "\n")


Expanded dims:
 [[1 2]] 

Expanded dims:
 [[1]
 [2]] 



## `squeeze`

In [48]:
# Removes single-dimensional entries from the shape
a = np.array([[[1,2,3], [4, 5 ,6]]])
print('a:\n', a, "\n", a.shape)
print('Squeezed:\n', np.squeeze(a), "\n",np.squeeze(a).shape)

a:
 [[[1 2 3]
  [4 5 6]]] 
 (1, 2, 3)
Squeezed:
 [[1 2 3]
 [4 5 6]] 
 (2, 3)


## `concatenate`

In [54]:
# Joins a sequence of arrays along an existing axis
b = np.array([[5, 6], [7, 8]])
a = np.array([[1, 2], [3, 4]])
print('Concatenated:\n', np.concatenate((b, a), axis=0))

Concatenated:
 [[5 6]
 [7 8]
 [1 2]
 [3 4]]


## `stack`

In [56]:
# Stacks arrays along a new axis
a = np.array([1, 2])
b = np.array([3, 4])
print('Stacked:\n', np.stack((a, b)))

Stacked:
 [[1 2]
 [3 4]]


## `hstack`

In [59]:
# Stacks arrays in sequence horizontally (column-wise)
a = np.array((1,2,3))
print(a)
b = np.array((4,5,6))
print(b)
print('Horizontally Stacked:', np.hstack((a,b)))

[1 2 3]
[4 5 6]
Horizontally Stacked: [1 2 3 4 5 6]


## `vstack`

In [61]:
# Stacks arrays in sequence vertically (row-wise)
a = np.array((1,2,3))
b = np.array((4,5,6))
print('Vertically Stacked:\n', np.vstack((a,b)))

Vertically Stacked:
 [[1 2 3]
 [4 5 6]]


## `dstack`

In [62]:
# Stacks arrays in sequence depth-wise (along third axis)
a = np.array((1,2,3))
b = np.array((4,5,6))
print('Depth Stacked:\n', np.dstack((a,b)))

Depth Stacked:
 [[[1 4]
  [2 5]
  [3 6]]]


## `column_stack`

In [64]:
# Stacks 1D arrays as columns into a 2D array
a = np.array((1,2,3))
b = np.array((4,5,6))
print('Column Stacked:\n', np.column_stack((a,b)))

Column Stacked:
 [[1 4]
 [2 5]
 [3 6]]


## `split`

In [77]:
# Splits array into multiple sub-arrays
a = np.arange(9)

for i in range(0, 9, 1) : 
    print(i + 1 ,":" ,np.split(a, 9)[i])

print("---------------")

for i in range(0, 3, 1) : 
    print(i + 1 ,":" ,np.split(a, 3)[i])

1 : [0]
2 : [1]
3 : [2]
4 : [3]
5 : [4]
6 : [5]
7 : [6]
8 : [7]
9 : [8]
---------------
1 : [0 1 2]
2 : [3 4 5]
3 : [6 7 8]


## `hsplit`

In [79]:
# Splits array into multiple sub-arrays horizontally (column-wise)
a = np.arange(16).reshape(4,4)
print('Horizontally Split:\n', np.hsplit(a,2))

Horizontally Split:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


## `vsplit`

In [83]:
# Splits array into multiple sub-arrays vertically (row-wise)
a = np.arange(16).reshape(4,4)
print('Vertically Split:\n', np.vsplit(a,2))

Vertically Split:
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## `dsplit`

In [84]:
# Splits array into multiple sub-arrays along the third axis
a = np.arange(16).reshape(2,2,4)
print('Depth Split:\n', np.dsplit(a,2))

Depth Split:
 [array([[[ 0,  1],
        [ 4,  5]],

       [[ 8,  9],
        [12, 13]]]), array([[[ 2,  3],
        [ 6,  7]],

       [[10, 11],
        [14, 15]]])]


## `resize`

In [86]:
# Resizes an array in-place (modifies original array)
a = np.array([[1,2],[3,4]])
a.resize((2,3))
print('Resized: \n', a)

Resized: 
 [[1 2 3]
 [4 0 0]]


## `append`

In [89]:
# Appends values to the end of an array
a = np.array([[1, 2], [3, 4]])
print('Appended: \n', np.append(a, [[5, 6]], axis=0))

Appended: 
 [[1 2]
 [3 4]
 [5 6]]


## `insert`

In [90]:
# Inserts values into an array at specified indices
a = np.array([[1, 2], [3, 4]])
print('Inserted: \n', np.insert(a, 1, [10, 10], axis=0))

Inserted: 
 [[ 1  2]
 [10 10]
 [ 3  4]]


## `delete`

In [91]:
# Deletes specified sub-arrays from an array
a = np.array([[1, 2], [3, 4]])
print('Deleted:', np.delete(a, 1, axis=0))

Deleted: [[1 2]]


## `unique`

In [92]:
# Finds the unique elements of an array
a = np.array([1,2,1,3,2])
print('Unique:', np.unique(a))

Unique: [1 2 3]
