# NumPy Array Manipulation - Examples with Comments

This notebook includes **examples and comments** for each function/method from the TutorialsPoint NumPy Array Manipulation guide.

In [ ]:
import numpy as np 

## `reshape`

In [ ]:
# Reshapes an array without changing its data
a = np.arange(6)
print('a:\n', a, "\n")
print('Reshaped: \n', a.reshape((2, 3))) 

## `flatten`

In [ ]:
# Returns a copy of the array collapsed into one dimension
a = np.array([[1, 2, 3], [4, 5, 6]])
print('a:\n', a, "\n")
print('Flattened:', a.flatten())

## `ravel`

In [ ]:
# Returns a flattened view of the array (if possible)
a = np.array([[1, 2], [3, 4]])
print('a:\n', a, "\n")
print('Raveled:', a.ravel())

## `transpose`

In [ ]:
# Permutes the dimensions of an array
a = np.array([[1, 2, 3], [4, 5, 6]])
print('a:\n', a, "\n")
print('Transposed: \n', np.transpose(a))

## `T`

In [ ]:
# Equivalent to transpose for 2D arrays
a = np.array([[1, 2], [3, 4]])
print('a:\n', a, "\n")
print('Transposed using .T:\n', a.T)

## `swapaxes`

In [ ]:
# Swaps two axes in an array
a = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print("ndim: ", a.ndim, "dims: ", a.shape, "\n")
print('a:\n', a, "\n")
print('Swapped Axes (0,2):\n', np.swapaxes(a, 0, 2))

## `broadcast`

In [ ]:
# Demonstrates implicit broadcasting in arithmetic operations
a = np.array([1,2,3])
b = np.array([[0],[1],[2]])
print('a:\n', a, "\n")
print('b:\n', b, "\n")
print('Broadcasted Sum:\n', a + b)

## `broadcast_to`

In [ ]:
# Explicitly broadcast an array to a given shape
a = np.array([1,2,3,4])
print('Broadcast to (3,3):\n', np.broadcast_to(a, (5,4)))

## `expand_dims`

In [ ]:
# Adds a new axis to an array
a = np.array([1, 2])
print('Expanded dims:\n', np.expand_dims(a, axis=0), "\n")
print('Expanded dims:\n', np.expand_dims(a, axis=1), "\n")


## `squeeze`

In [ ]:
# Removes single-dimensional entries from the shape
a = np.arange(6).reshape((2, 1, 3))
print('a:\n', a, "\n", a.shape)
print('Squeezed:\n', np.squeeze(a), "\n",np.squeeze(a).shape)

a:
 [[[0 1 2 3 4 5]]] 
 (1, 1, 6)
Squeezed:
 [0 1 2 3 4 5] 
 (6,)


## `concatenate`

In [ ]:
# Joins a sequence of arrays along an existing axis
b = np.array([[5, 6], [7, 8]])
a = np.array([[1, 2], [3, 4]])
print('Concatenated:\n', np.concatenate((b, a), axis=0))

## `stack`

In [96]:
# Stacks arrays along a new axis
a = np.array([1, 2])
b = np.array([3, 4])
print('Stacked:\n', np.stack((a, b)))

Stacked:
 [[1 2]
 [3 4]]


## `hstack`

In [ ]:
# Stacks arrays in sequence horizontally (column-wise)
a = np.array((1,2,3))
print(a)
b = np.array((4,5,6))
print(b)
print('Horizontally Stacked:', np.hstack((a,b)))

## `vstack`

In [ ]:
# Stacks arrays in sequence vertically (row-wise)
a = np.array((1,2,3))
b = np.array((4,5,6))
print('Vertically Stacked:\n', np.vstack((a,b)))

## `dstack`

In [ ]:
# Stacks arrays in sequence depth-wise (along third axis)
a = np.array((1,2,3))
b = np.array((4,5,6))
print('Depth Stacked:\n', np.dstack((a,b)))

## `column_stack`

In [ ]:
# Stacks 1D arrays as columns into a 2D array
a = np.array((1,2,3))
b = np.array((4,5,6))
print('Column Stacked:\n', np.column_stack((a,b)))

## `split`

In [ ]:
# Splits array into multiple sub-arrays
a = np.arange(9)

for i in range(0, 9, 1) : 
    print(i + 1 ,":" ,np.split(a, 9)[i])

print("---------------")

for i in range(0, 3, 1) : 
    print(i + 1 ,":" ,np.split(a, 3)[i])

## `hsplit`

In [ ]:
# Splits array into multiple sub-arrays horizontally (column-wise)
a = np.arange(16).reshape(4,4)
print('Horizontally Split:\n', np.hsplit(a,2))

## `vsplit`

In [ ]:
# Splits array into multiple sub-arrays vertically (row-wise)
a = np.arange(16).reshape(4,4)
print('Vertically Split:\n', np.vsplit(a,2))

## `dsplit`

In [ ]:
# Splits array into multiple sub-arrays along the third axis
a = np.arange(16).reshape(2,2,4)
print('Depth Split:\n', np.dsplit(a,2))

## `resize`

In [ ]:
# Resizes an array in-place (modifies original array)
a = np.array([[1,2],[3,4]])
a.resize((2,3))
print('Resized: \n', a)

## `append`

In [ ]:
# Appends values to the end of an array
a = np.array([[1, 2], [3, 4]])
print('Appended: \n', np.append(a, [[5, 6]], axis=0))

## `insert`

In [ ]:
# Inserts values into an array at specified indices
a = np.array([[1, 2], [3, 4]])
print('Inserted: \n', np.insert(a, 1, [10, 10], axis=0))

## `delete`

In [ ]:
# Deletes specified sub-arrays from an array
a = np.array([[1, 2], [3, 4]])
print('Deleted:', np.delete(a, 1, axis=0))

## `unique`

In [ ]:
# Finds the unique elements of an array
a = np.array([1,2,1,3,2])
print('Unique:', np.unique(a))