# NumPy: Sort, Search & Counting Functions
Summary and examples based on Tutorialspoint's guide.

In [ ]:
import numpy as np

## numpy.sort
Sorts an array.
```python
numpy.sort(a, axis=-1, kind='quicksort', order=None)
```

In [ ]:
arr = np.array([[3, 2, 1], [6, 5, 4], [-1, 0, -2]])
print(arr, "\n------------")
print(np.sort(arr, kind='heapsort', axis=1))


dt = np.dtype([('name', 'U20'), ('age', np.int64)])
a = np.array([("Arshiya", 20), ("Bita", 24), ("Hesam", 23), ("Ali", 20), ("Amin", 22),("Maryam", 19),
              ("Sara", 20), ("Reyhan", 20), ("Yasin", 23), ("Dakik", 23), ("رییسی", 23), ("Pouria", 23),("Saman", 22)], dtype=dt)
print("Original:",a,"\n--------------------------------------------")
print("Order by name:",np.sort(a, order='name'))

## Sorting another custom list

In [ ]:
# Define structured array with named fields
tp = np.dtype([('x', np.int32), ('y', np.int64)])
data = np.array([(1, 9), (3, 4), (2, 8)], dtype=tp)

# Sort by the 'y' field (second element)
sorted_data = np.sort(data, order='y')
print(sorted_data)


## numpy.argsort
Returns indices that would sort an array.
```python
numpy.argsort(a, axis=-1, kind=None, order=None)
```

In [ ]:
arr = np.array([3, 1, 2])
np.argsort(arr)

## numpy.lexsort
Sorts using multiple keys.
```python
numpy.lexsort(keys, axis=-1)
```

In [ ]:
names = ('john', 'smith', 'john')
ages = (25, 30, 20)
ind = np.lexsort((ages, names))
ind

## numpy.argmax / numpy.argmin
Return indices of max/min elements.
```python
numpy.argmax(a, axis=None)
numpy.argmin(a, axis=None)
```

In [ ]:
import random 
ran = np.random.rand(10)
for i in range(0, ran.shape[0]) : 
    ran[i] *= 10
ran = np.int32(ran)
print(ran) 

Max = np.argmax(ran)
Min = np.argmin(ran)

print(Max, ": ", ran[Max])
print(Min, ": ", ran[Min])

## numpy.nonzero
Returns indices of non-zero elements.
```python
numpy.nonzero(a)
```

In [ ]:
arr = np.array([[0, 1, 0], [2, 0, 3]])
print(arr.shape)
print(np.nonzero(arr))

## numpy.searchsorted
Finds indices to maintain order.
```python
numpy.searchsorted(a, v, side='left', sorter=None)
```

In [ ]:
arr = np.array([1, 3, 5])
np.searchsorted(arr, 4)

## numpy.where
Finds the indices that satisfy a given condition 

In [28]:
tst = np.arange(12).reshape((3, -1))

con = np.where(tst % 3 == 0)

print(tst[con])


## where(condition, replace if condition satisfied, repleace if condition not satisfied)

print(np.where(tst%3==0, tst, 100))



[0 3 6 9]
[[  0 100 100   3]
 [100 100   6 100]
 [100   9 100 100]]


## numpy.extract

In [ ]:
import numpy as np

arr = np.array([[0, 1, 2],
                [3, 4, 5]])

# Condition: elements divisible by 2
np.extract(arr % 2 == 0, arr)
